<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PekerjaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pekerjaan = [
            'Dokter',
            'Guru',
            'Insinyur',
            'Perawat',
            'Polisi',
            'Akuntan',
            'Programmer',
            'Arsitek',
            'Penulis',
            'Seniman',
            'Pengacara',
            'Koki',
            'Ahli keuangan',
            'Ilmuwan',
            'Pekerja sosial',
            'Peneliti',
            'Teknisi',
            'Pemadam kebakaran',
            'Manajer proyek',
            'Penjual retail',
            'Pelatih olahraga',
            'Manajer sumber daya manusia (SDM)',
            'Analis data',
            'Desainer grafis',
            'Fotografer',
            'Teknisi jaringan komputer',
            'Konsultan manajemen',
            'Pengembang web',
            'Penyiar radio/televisi',
            'Montir mobil/motor',
            'Petani',
            'Pustakawan',
            'Desainer interior',
            'Operator mesin',
            'Jurnalis',
            'Perancang mode',
            'Ahli terapi fisik',
            'Pengusaha',
            'Asisten rumah tangga',
            'Pilot',
            'Pramugari/pramugara',
            'Karyawan administrasi',
            'Sales/marketing',
            'Ahli biologi',
            'Astronom',
            'Ahli kimia',
            'Juru teknik',
            'Psikolog',
            'Penyiar radio/televisi',
            'Translator/interpreter',
            'Pilot drone',
            'Manajer restoran',
            'Ahli nutrisi/dietisien',
            'Perancang permainan video',
            'Pengajar musik',
            'Ahli forensik',
            'Konsultan keuangan',
            'Pengelola acara',
            'Petugas layanan pelanggan',
            'Konsultan kecantikan',
            'Ahli hukum lingkungan',
            'Ahli farmasi',
            'Ahli bedah',
            'Petugas penegakan hukum',
            'Spesialis pengembangan masyarakat',
            'Arsitek lanskap',
            'Ahli patologi',
            'Animator',
            'Ahli bioteknologi',
            'Ahli meteorologi',
            'Peneliti pasar',
            'Ahli genetika',
            'Ahli ekonomi',
            'Fotografer pernikahan',
            'Ahli zoologi',
            'Ahli kesehatan masyarakat',
            'Ahli psikiatri',
            'Konsultan teknologi informasi',
            'Ahli antropologi',
            'Ahli pariwisata',
            'Ahli astronomi',
            'Analis risiko',
            'Ahli etnografi',
            'Ilustrator',
            'Pengacara properti',
            'Ahli demografi',
            'Penulis teknis',
            'Spesialis kepatuhan',
            'Ahli bioinformatika',
            'Ahli robotika',
            'Geolog',
            'Ahli pertanian',
            'Ahli pengembangan produk',
            'Ahli kebijakan publik',
            'Penulis konten digital',
            'Ahli paleontologi',
            'Ahli radiologi',
            'Ahli proteomics',
            'Ahli tokoh masyarakat',
            'Perencana keuangan',
        ];

        foreach ($pekerjaan as $nama_pekerjaan) {
            DB::table('pekerjaan')->insert([
                'jenis_pekerjaan' => $nama_pekerjaan,
            ]);
        }
    }
}
